github.com:
    users:
        FrackinFamous:
            oauth_token: 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
    git_protocol: https
    user: FrackinFamous
    oauth_token: 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
